export const browserCoreExamples = [
  "quantumclaw browser status",
  "quantumclaw browser start",
  "quantumclaw browser stop",
  "quantumclaw browser tabs",
  "quantumclaw browser open https://example.com",
  "quantumclaw browser focus abcd1234",
  "quantumclaw browser close abcd1234",
  "quantumclaw browser screenshot",
  "quantumclaw browser screenshot --full-page",
  "quantumclaw browser screenshot --ref 12",
  "quantumclaw browser snapshot",
  "quantumclaw browser snapshot --format aria --limit 200",
  "quantumclaw browser snapshot --efficient",
  "quantumclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "quantumclaw browser navigate https://example.com",
  "quantumclaw browser resize 1280 720",
  "quantumclaw browser click 12 --double",
  'quantumclaw browser type 23 "hello" --submit',
  "quantumclaw browser press Enter",
  "quantumclaw browser hover 44",
  "quantumclaw browser drag 10 11",
  "quantumclaw browser select 9 OptionA OptionB",
  "quantumclaw browser upload /tmp/quantumclaw/uploads/file.pdf",
  'quantumclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "quantumclaw browser dialog --accept",
  'quantumclaw browser wait --text "Done"',
  "quantumclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "quantumclaw browser console --level error",
  "quantumclaw browser pdf",
];
